from intervals.models import Interval

Interval.objects.all().delete()

Interval.objects.create(semitones=0, up=True, name="unison")
Interval.objects.create(semitones=1, up=True, name="minor second")
Interval.objects.create(semitones=2, up=True, name="major second")
Interval.objects.create(semitones=3, up=True, name="minor third")
Interval.objects.create(semitones=4, up=True, name="major third")
Interval.objects.create(semitones=5, up=True, name="perfect fourth")
Interval.objects.create(semitones=6, up=True, name="diminished fifth")
Interval.objects.create(semitones=7, up=True, name="perfect fifth")
Interval.objects.create(semitones=8, up=True, name="minor sixth")
Interval.objects.create(semitones=9, up=True, name="major sixth")
Interval.objects.create(semitones=10, up=True, name="minor seventh")
Interval.objects.create(semitones=11, up=True, name="major seventh")
Interval.objects.create(semitones=12, up=True, name="octave")

Interval.objects.create(semitones=-1, up=False, name="minor second")
Interval.objects.create(semitones=-2, up=False, name="major second")
Interval.objects.create(semitones=-3, up=False, name="minor third")
Interval.objects.create(semitones=-4, up=False, name="major third")
Interval.objects.create(semitones=-5, up=False, name="perfect fourth")
Interval.objects.create(semitones=-6, up=False, name="diminished fifth")
Interval.objects.create(semitones=-7, up=False, name="perfect fifth")
Interval.objects.create(semitones=-8, up=False, name="minor sixth")
Interval.objects.create(semitones=-9, up=False, name="major sixth")
Interval.objects.create(semitones=-10, up=False, name="minor seventh")
Interval.objects.create(semitones=-11, up=False, name="major seventh")
Interval.objects.create(semitones=-12, up=False, name="octave")
